[package]
name = "lazytest"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.38", default-features = false, features = ["load_extension"] }
libsqlite3-sys = { version = "0.36" }
